### ISSUE TITLE
Migrate docs from readthedocs to docusaurus

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#105]
###  Problem

The HOPR docs, hosted at [docs.hoprnet.org](https://docs.hoprnet.org), are currently built on the [readthedocs](https://readthedocs.org/) platform, created at very short notice in Jan 2021 when the previous version, built on gitbook, broke and gitbook failed to respond. The docs are outdated and not very accessible for either community members who want to read it or the commercial team who want to update it

### Proposed Solution

We propose migrating them to the [docusaurus](https://docusaurus.io/) platform, updating and streamlining the content, and combining with some content from the [HOPR Basics](https://medium.com/hoprnet/hopr-basics-episode-1-what-is-hopr-7d8cc4daf014) series. This would make the docs a general educational platform to benefit community members with a variety of technical expertise.

Docusaurus seems to be an easier platform for the comm team to use than readthedocs, but this solution would require initial input from tech team to migrate to new platform.

### Alternate Solution

We could stick with readthedocs until tech team has more bandwidth to assist. It doesn't really fit our medium or long-term goals for the [docs.hoprnet.org](https://docs.hoprnet.org) page, but we have successfully made minor updates in the past.

-----------

### Implementation Details

Docusaurus is a tool for generating a static page. So when you change something in files, you just build static pages which you can run locally to check if it is working properly and then push to Github.

The implementation plan would be:

- We would like to use a DO (DigitalOcean) server, so both tech and comm team have ability to access to it.
- Run a Docker to serve the static page.
- We'd push from our DO server to github for any changes we make.
- From github side when someone changes files or content it should create an image and push it to DO registry.
- DO Docker would monitor for a new version from DO registry and update if needed.

We can make changes from a server and push to the github branch and then merge. Or we can directly change on github and make a PR.

**Comment by nionis** [comment]
Thanks for creating the issue @thewanderingeditor!
Generally, is better to have proposed ideas written down as it helps everybody get a picture of what the proposal looks like.

For me, as a representative of the tech team, it's extremely important to make sure there are no unexpected upcoming workloads that may require tech resources which ultimately will lead to overutilizing the tech team that will not only cause delays but also burnout.
It's often hard to sometimes determine beforehand whether a task will not affect certain areas of the company (in this example tech), so writing the said task down is the best tool we can use to ensure we got it all sorted and planned out in the best of our ability.

I personally have no problem switching to a new system that makes it easier for other team members to contribute to the docs.
However, we need to make sure that migrating to this new system doesn't break any of the existing properties that the current system has.

I think it's easier for me to least write here what I think the system must have in my view:

| Column | Description |
| -------- | ------------ |
| Easy to edit by non-tech | It's primarily easy for non-techies to rapidly develop and modify the documentation |
| Easy to edit by tech | It's primarily easy for techies to ensure documentation is updated per PR basis |
| Synced with codebase | Docs follow the same versioning as our codebase |

| Solution | Easy to edit by non-tech | Easy to edit by tech |  Synced with codebase |
| ----------- | ----------- | ----------- | ----------- |
|  readthedocs (current) |  ❌ | ✔ | ✔ (master & release) |
|  proposed |  ✔ | ❌ | ❌ |
| ideal | ✔ | ✔ | ✔ |

Ultimately, using these tables as guides, to me at the least, means that if we _do_ decide to proceed with the proposed solution, we need to ensure that we include a process for the tech team to keep the docs updated outside of the `monorepo`.

| Solution | Easy to edit by non-tech | Easy to edit by tech |  Synced with codebase | No process required |
| ----------- | ----------- | ----------- | ----------- | ----------- |
|  readthedocs (current) |  ❌ | ✔ | ✔ | ✔ |
|  proposed |  ✔ | ❌ | ❌ | ❌ |
| ideal | ✔ | ✔ | ✔ | ✔ |

Now, am not against switching to [docusaurus](https://docusaurus.io/) or any other tool that has been researched and considered an improvement over `readthedocs`, we just need to make sure that the proposal doesn't take a step back.

Would it be possible to modify the proposal to include the whole implementation plan? This way we can determine more accurately if the proposed solution truly contains these negatives or maybe it's my misunderstanding of the proposal, the proposal itself lacks deeper implementation details which would clarify this.

Anyhow, I want to make sure you guys understand that am `100%` in for changing to something _better_, it's just in my experience the devil is in the details.

**Comment by thewanderingeditor** [comment]
I think @Jaguaras is best placed to add details of the full implementation plan.

I'm a bit surprised by how you've filled out the table. My understanding was the readthedocs **wasn't** properly synced with the codebase, and actually that's why we had problems in Wildhorn v2 with users ending up on the wrong version.

I'm also surprised at the assessment that docusaurus would be hard for tech to edit. Wouldn't it integrate with github in the same way readthedocs does?

**Comment by nionis** [comment]
That's a misunderstanding, `readthedocs` syncs `master` and one specified release, the issue was that we had no processes during `wildhorn-v2` (we merged the new processes the release after) so the `readthedocs` release wasn't pointing to the new version.

> Wouldn't it integrate with github in the same way readthedocs does?

Perhaps, that's why am asking for implementation details. We can't operate with optimistic assumptions.
This is the core of my issue in general, the claim was that this would involve very little tech resources, let's make sure that's the case.

**Comment by nionis** [comment]
I hope that the fact that am picking on this topic is not misunderstood, I _want this_ too, just need to make sure we don't go ahead with a direction that will result in a net negative result, that's all. I appreciate you guys taking the initiative to fix the docs.
I don't want to be presumptuous, but I think _we_ as humans have the tendency to oversimplify ideas in our head, but when put to practice, in my experience, it's often not as simple.

For me personally, I would be more than happy and give you my blessing when we can be assured that the points said above are covered. 👍

**Comment by Jaguaras** [comment]
Thanks guys for bringing up the discussion about the docs page.

First of all Docusaurus is a tool for generating a static page. So when you change something in files, you just build static pages which you can run localy to check if it is working properly and then push to the github. So there should not be any issues to edit for tech and non-tech team.

Implementation plan would be:

1. We would like to use a DO (DigitalOcean) server, so even tech team could also have ability to access to it.
2. Run a Docker to serve the static page.
3. We can push from our DO to github for any changes we made.
4. From github side when someone is changes files or content it should create an image and push it to DO registery.
5. DO Docker monitors for a new version from DO registery and updates it if needed.

What we can see here is that we can do changes from a server and push to the github branch and then merge. Or we can directly change on github and PR.

**Comment by Jaguaras** [comment]
Also let me add the docusaurus breif explaination on the install process: https://docusaurus.io/docs/installation
Here is the deployment options: https://docusaurus.io/docs/deployment

**Comment by nionis** [comment]
@Jaguaras A clarification, `Easy to edit by tech` stands for `It's primarily easy for techies to ensure documentation is updated per PR basis` as described in the table, has nothing to do with preview ability, actually `readthedocs` works the same as you describe, you can also build static pages locally.

In any case, am happy to see that the proposal takes into account the other mentioned aspects, would it be possible for you to update the description of the issue? You can make a line and add it as an update.

I would keep this issue alive in the repository, and close it once the PR is merged replacing `readthedocs` with `docusaurus`.

**Comment by Jaguaras** [comment]
@nionis Thanks, sure @thewanderingeditor will update the description of the issue. I would like to have a call to talk about the implementation process. Let me know who would like to be involved and when it is a proper time?

**Comment by nionis** [comment]
Let's set up a call next week, u can invite the representatives, one or both will join.

**Comment by thewanderingeditor** [comment]
I updated the original description with @Jaguaras implementation comments (with minor edits for clarity)

**Comment by tolbrino** [comment]
Closing this since the migration has been completed to use the new framework.
