### ISSUE TITLE
Mint NFTs for DAO v0.2 experiment

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#107]
Participants in the HOPR DAO v0.2 experiment earned NFTs for their interactions on the forum and voting on snapshot.

The data has been aggregated and the addresses collected. All that remains is to mint and distribute them.

This can be done once @thewanderingeditor and @Eleonora0119 have been onboarded to the minting process, described in issue #106.

**Comment by QYuQianchen** [comment]
NFTs are minted. Pictures are not yet hosted.

**Comment by QYuQianchen** [comment]
Pictures look good. An example [pic](https://blockscout.com/xdai/mainnet/token/0x43d13D7B83607F14335cF2cB75E87dA369D056c7/instance/8912/metadata)
