### ISSUE TITLE
Job Description & Personal Sentence for the Website & Socials

### ISSUE THREAD

**Issue by jayveq** [hoprnet/hopr-devrel#116]
### Issue deadline

Nov 26 2021

### Detailed Description

For our website and future bi-weekly posts, as proposed by Rik, we need little information from each member of the tech team — ideally sourced in one single document: https://docs.google.com/spreadsheets/d/1pMwGxEg-AVhwAC0BvtVUBvBLrOmkhJhkBkW2C971cnI/edit?usp=sharing

- First, we need to know if each specific team member wants to be shown with a picture or our anonymous avatars. We don't want to force anyone who doesn't want to, to be shown with their face somewhere.

- Additionally, I'd like every tech team member by themselves or one organizing team member to check the prefilled specific Job Titles of each member (or fill in the missing ones I couldn't find on the website) and add a short explanatory description of their specific tasks. (One or two small sentences are sufficient!)

- At last, we want a few small personal sentences from each team member, as well as possible socials, they want to have linked (potentially on the website, but definitive in upcoming social media posts) if at all.

If there's any person missing or prefilled information incorrect, feel free to add/change those specific fields. Also, if there are any questions, please contact me.

**Comment by jjperezaguinaga** [comment]
@sirjaycrypto

1. Sure :)
2. Let's use `Head of Engineering` unless suggested something else by @SCBuergel 
3. `Jose is a software engineer with 10+ years of experience in all web-related technologies, particularly on JavaScript/Typescript and node.js.  He's a cryptography enthusiast with a BS in Computer Science from ITESM CQ, and has been working in web3 for multiple startups since 2017.`

**Comment by SCBuergel** [comment]
@jjperezaguinaga pls fill into the Google doc and not here (there's some other stuff there as well)

**Comment by tolbrino** [comment]
outdated
