### ISSUE TITLE
Diagnose and resolve issue in DAO payouts

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#121]
### Issue deadline

Monday 29th for data gathering. Wednesday 31st for reward distribution

### Detailed Description

Five DAO forum participants didn't receive testnet rewards or NFTs: https://docs.google.com/spreadsheets/d/1IQ8xb3s7lOnv5oS4Eit1vnKkqQSiKwwhQUPVWtu2u2U/edit#gid=0

It seems they didn't fill in their NFT address field; however, they did have a filled DAO address field, and my understanding was that those had been used in cases where the NFT address was missing. I'd like to work out what went wrong and identify any other missing people.

Separately, since the instructions weren't completely clear and these users did participate in the forum. I'd like to make sure they get their rewards. This means minting some more DAO v2 NFTs and adding these payouts to the distributor schedule.

**Comment by QYuQianchen** [comment]
RE NFT, could you please provide the "type/rank/APY" as indicated in the [issue template](https://github.com/hoprnet/hopr-devrel/issues/new?assignees=&labels=&template=request-for-minting-hoprboost-nft.md&title=%5BRFM%5D)? Despite it should be the same as previously-minted NFTs, stating those parameters is less error-prone.

**Comment by QYuQianchen** [comment]
Can @Eleonora0119 give the link to the DAO v0.2 payout analysis, so that @Jaguaras can find out the amount of token payouts each missing address should have? Given the analysis is already done, we just need to map the `userId` with `address` in the result list.

**Comment by Eleonora0119** [comment]
The python file of the evaluation is available here: https://github.com/hoprnet/hopr-devrel/blob/main/analytics/dao_v02_eval/dao_eval_with_distribution.ipynb
And you find all the input files here: https://drive.google.com/drive/folders/1r7N8_qCsv7BczegBA54bD1okcGNSPpGK
If they are not on the NFT list unfortunately it can happen that they participated, but commented on a non-valid (or non-valid anymore) proposal hence they did not show up in the evaluation at all.

**Comment by Eleonora0119** [comment]
Is any further help needed?

**Comment by thewanderingeditor** [comment]
No, this was resolved. Thanks!
