### ISSUE TITLE
[RFM]

### ISSUE THREAD

**Issue by Jaguaras** [hoprnet/hopr-devrel#122]
### When should NFTs be minted?

Nov 26 2021
### Which type, rank and apy do NFTs have?

| BoostType 	| Rank 	| APY 	|
|-----------	|------	|-----	|
| Wildhorn_v2   | diamond | 7.5 |
| Wildhorn_v2   | gold    | 6   |
| Wildhorn_v2   | silver    | 4.5   |
| Wildhorn_v2   | bronze    | 3   |

### Please upload export csv files

I confirm that
- [v] Column `eoa` and `grade` are mandatory
- [v] Addresses in the column `eoa` should start with `0x` and wrapped by `>` and `<`. The followings are valid examples of an `eoa` entry: 
    - `"<a href=""https://blockscout.com/xdai/mainnet/address/0xf69c45b4246fd91f17ab9851987c7f100e0273cf"" target=""_blank"">0xf69c45b4246fd91f17ab9851987c7f100e0273cf</a>"` 
    - `>0xea674fdde714fd979de3edf0f56aa9716b898ec8<`

[Wildhorn_v2.csv](https://github.com/hoprnet/hopr-devrel/files/7607992/Wildhorn_v2.csv)

**Comment by QYuQianchen** [comment]
https://blockscout.com/xdai/mainnet/tx/0xe747977ff372030ae34c7c4e571d74875684459d09ea3db3b17106ba70117d05
https://blockscout.com/xdai/mainnet/tx/0x6da766d3b3762131ccb2ca13d8cea3749d52908899ded9eaf4d53f5b0df90536
https://blockscout.com/xdai/mainnet/tx/0x99db505042603eef03a8586ff9bddf07e1ecf34fd591a65bbbb2710ece2860a8
https://blockscout.com/xdai/mainnet/tx/0x7c899a295dda1e138266b65a349a199cd3d1bd1ba53add369ffa061046c9d82e
