### ISSUE TITLE
Dedicated Dune dashboard for staking season 2

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-devrel#165]
### Issue deadline
March 31 2021

### Detailed Description
Create a dashboard on DuneAnalytics for Staking program season 2 (S2), similar to [the dashboard for Staking season 1 (S1)](https://dune.xyz/hoprnet/HOPR-Staking-Program).

Note that:
1. There is no `virtualStake` in season 2.
2. One more table is needed, to extract a list of `accounts` who have redeemed HoprBoost NFTs but has nothing at stake, together with the `tokenId` of redeemed NFTs. (A similar query for S1 can be found [here](https://dune.xyz/queries/361226)) 
3. Change table from `hopr_protocol."HoprStake_evt_Staked"` to `hopr_protocol."HoprStake2_evt_Staked"`

**Comment by Eleonora0119** [comment]
Further modifications:
- hopr_protocol."HoprStake.. to hopr_protocol."HoprStake2..
- date of start, seed and end:
1627387200 AS basic_start, 
1630065600 AS seed_start,
1642424400 AS program_end,

**Comment by QYuQianchen** [comment]
I did a quick check on the rewards of S2, and thus created a [draft "StakingS2 rewards - overview" query](https://dune.xyz/queries/374451). Please extend the query for "overview"

**Comment by Eleonora0119** [comment]
The dashboard is available: https://dune.xyz/hoprnet/HOPR-Staking-Program-Season-2
Need to be checked/validated: 
- it's private so far
- new NFT table's query (Redeemed NFTs without stakeNFT rescue part 2 - redeemed without stake v2)
- position of tables and charts (tables related to the virtual stake were removed)
- the link of the Details has been changed to the actual one: https://medium.com/hoprnet/hopr-staking-2-0-6e79dbf66827
