### ISSUE TITLE
ETH Denver HOPR DevRel tasks

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-devrel#166]
# Background

HOPR is a Meta sponsor of [ETH Denver](https://www.ethdenver.com/), where we'll be giving a workshop and throwing a few bounties to attendees to develop on top of the HOPR network. To max out our exposure for the duration of the event, we need to polish a few resources and tools to ensure seasoned developers and newcomers alike can develop HOPR apps.

# Introduction

As discussed with @SCBuergel, the main three points we want to tackle are the following:

- **HOPR Local Cluster Setup**: Without a fully interconnected HOPR network, there's very little thing developers can do on top of HOPR. There's a script created by @tolbrino to make it as easy as possible to run a fully connected HOPR network, but that currently lives in our `hoprnet` monorepo, which requires users to install dependencies, build, and run the scripts, which isn't ideal for a hackathon with limited time span. 
- **Documentation for WebSocket Client**: Given a running HOPR node, any person can use the API documentation to send HTTP responses. However, they won't be able to see anything because that's only listened to the node's WebSocket server. For that, we need to connect a WebSocket client which isn't immediately obvious, and more important, isn't documented at all.
- **Hello world for HOPR Apps**: Right now, MyneChat works more as a demo of HOPR tech than as a starting point for building an app on top of the HOPR network. For that to work, we need to create some basic “hello world” like a setup that can be completed in 5 minutes for anyone to understand what HOPR is all about.

# Tasks

**HOPR Local Cluster Setup**
- [x] https://github.com/hoprnet/hoprnet/issues/3329
- [x] #167
- [x] #168
- [x] #169
- [x] #170

**Documentation for WebSocket Client**
- [x] #175
- [x] #176
- [x] #177

**Hello world for HOPR Apps**
- [x] #172
- [x] #173
- [x] #174

# Bugs found during epic
- #179
- [x] #186

# New issues outside of the original scope

- #183
- #184
- #185
- [x] #189

# Definition of done

This epic is completed when the three following tasks are completed:

* An entire interconnected HOPR network can be launched with a single command via the terminal, and a local MyneChat instance can connect to two of these clients and send messages across them.
* `docs.hoprnet.org` has documentation on how to read messages from a node sent via its API via some cli or cloud utility
* The `3` examples on how to send/write messages on top of HOPR are publicly available and can be run either locally or seen via a publicly available web URL.

# Testing criteria

- Anyone in the comms team can run a fully interconnected network locally or via the cloud
- Given a running local HOPR cluster, anyone in the comms team can send API messages and read them through some util
- Anyone in the tech team not involved in MyneChat or API can complete with the three demos
- Thumbs up from @SCBuergel

**Comment by SCBuergel** [comment]
@jjperezaguinaga actually this is an epic with deadline for Feb 7, so that our two Hackathon Supporters have at least 3 days to review and familiarize themselves with the materials and potential debugging (see https://github.com/hoprnet/hopr-devrel/issues/171)

**Comment by jjperezaguinaga** [comment]
Everything has been now completed, the only lag came from #167 which was a minor one. Closing to double-check acceptance.
