### ISSUE TITLE
Create a simple one-line command to create a HOPR local network locally

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-devrel#168]
**Goal**
To onboard developers as soon as possible with an easy-to-use command that anyone can use in any OS distribution such as a HOPR local network can be quickly spun up without them having to worry about the details.

**Task Description**
Create a single entry point binary `./start-network` which spins up a specific version of HOPR nodes and funds them, while `echo`ing the URLs where they are available.

**Comment by SCBuergel** [comment]
For any supported OS which IIRC is: macOS, most Linux distros, Windows & WSL2, right? Would be good to add a check for each OS and document how to start in each OS if there's any non obvious additional quirks, requirements or dependencies

**Comment by jjperezaguinaga** [comment]
Agreed, ideally, we compile this in a way that can be used across any of the major OS.

**Comment by jjperezaguinaga** [comment]
PR https://github.com/hoprnet/hoprnet/pull/3103 has been merged and further work now will be done to start the `hoprd` instances manually via a `nodejs` cli tool. We still don't have a way to spin up an RPC node easily, though, as reported in #179

**Comment by jjperezaguinaga** [comment]
We are closing this one for now, the main reason is that despite any optimization we might make here, we still rely on our RPC endpoint, which as of time of writing can only be spun up with our monorepo as described in #179.

We did some work[^1] in https://github.com/hoprnet/hoprnet/pull/3103 that alongside the following tweaks were good enough to get our `hoprnet` repo from `~30mb` to `~4mb`, and from there one can do `yarn workspaces focus` inside`packages/ethereum` and then `yarn build` inside`packages/utils`, which exposes `yarn network` and `yarn faucet` within `packages/ethereum`.

However, even w/the whole monorepo optimized, installing the utilities via `yarn` adds an extra `~800mb`, not to mention the build/install time. This is mainly due to `packages/ethereum` using `@hoprnet/hopr-utils` like three times , which we aren't tree shaking properly so there's that.

### Intended goal

Ideally, we would have three setups:
1. Challenging environment (i.e. low cpu, low internet connection)
2. Advanced environment (i.e. high cpu, high internet connection)
3. Cloud environment (i.e. low cpu, medium internet connection)

We simply can't work around `(1)` for now as even pruning our repo (i.e. from `21 mbs zipped -> 4 mbs`) we can't work around a huge `yarn`. Our `hoprd` nodejs standalone port (e.g. see an [example](https://github.com/hoprnet/hoprnet/blob/master/packages/hoprd/src/main.ts) from our latest merged PR) would still face the same issue. We can ask users to pre-install and pre-build, but realistically speaking that won't happen.

For `(2)` it makes no sense to over optimise, as they can simpley clone our monorepo and go ahead with the full process. It's not ideal, but in my mac (which is an ok-ish benchmark for hackathon attendees), this takes roughly 5-10min, they can go for a coffee. For them, we can simply do `yarn && yarn build && setup-local-cluster`, which I've already documented in [this](https://github.com/hoprnet/hoprnet/pull/3346) PR.

For `(3)` we will do Gitpod, which I've also documented in our [MyneChat .gitpod.yml](https://github.com/hoprnet/myne-chat/blob/develop/.gitpod.yml), so we'll just focus on having a similar setup for the app templates.

So the outcome is simply that for the time being, we can't do a one-liner setup w/o significant efforts. Instead, for devs looking to use a local setup, we should warn them of build time and high internet requirements. Everyone else can use our Gitpod setup. This documentation is already in a [PR](https://github.com/hoprnet/hoprnet/pull/3346), pending to be merged.

As a last note, there's an open PR (https://github.com/nomiclabs/hardhat/issues/652) on the `hardhat` snapshot saving feature which in the future could help us via a Docker-based setup similar to [this one](https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/ethereum-test-node/Dockerfile).

[^1]: pruned, history-less,`docs/`-less, wget-ed zip version of our repo (e.g. https://github.com/jjperezaguinaga/hoprnet)
