### ISSUE TITLE
Ethereum network with deployed contracts require monorepo setup

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-devrel#179]
## Expected behaviour

Ideally, I'm able to quickly spin a `hardhat` instance with the deployed contracts for the HOPR network in an isolated fashion (e.g. via a cli tool a la `./start-network.sh`). Then, I can point my RPC provider client to the URL created there, and start interacting with the `HoprToken` and `HoprChannels`

## Current behaviour

To start the network, one has to clone the [HOPR monorepo](https://github.com/hoprnet/hoprnet), install all the dependencies across the project, build it, and then run `yarn run:network` from the workspace root to be able to expose this instance. The setup time to do this is too extensive (e.g. ~5-10 min build time) and could produce an error on a protocol level which could put off app developers.

## Steps to reproduce

1. Try to run an RPC provider instance w/o cloning the monorepo.

## Suggested solutions

The following solutions were shared internally in our `#tech` channel:

1. Having some sort of`db` we can do`hardhat --db=$url/db-with-deployed-contracts` similar to [ganache's `database.dbPath`](https://github.com/MyBitFoundation/MyBit-Chain.tech/blob/8b727dbb092e59375ac1a0614b538d8c8f402bd9/chain.js#L5-L14).
2. Pre-build a [docker image](https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/ethereum-test-node/Dockerfile) with`ganache` + contracts deployed, nodes funded (we would need to use fixed accounts and pass them to`hoprd` nodes via`--privateKey`).
3. Pre-build a docker image with our`packages/hardhat` to do deploy/fund from there as to avoid having people to download the entire monorepo. Right now we are building our Docker images via our a [script](https://github.com/hoprnet/hoprnet/blob/755a6923eb116af41b83515605b9ad9c67715031/scripts/build-docker.sh).

**Comment by jjperezaguinaga** [comment]
To avoid having to jump between issues, here are the most important links related to this issue:

- Open issue discussing how to enable this on `hardhat` https://github.com/NomicFoundation/hardhat/issues/652
- An example of this working via Truffle - https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/ethereum-test-node/Dockerfile

For now, let's move this to `icebox` until this issue is tackled there.
