### ISSUE TITLE
[RFM]

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-devrel#180]
### When should NFTs be minted?
Feb 8 2022

### Which type, rank and apy do NFTs have?
| BoostType     | Rank    | APY |
|---------------|---------|-----|
| ETH_Denver   | hacker | 2 |

### Please upload export csv files
300 NFTs minted into the Gnosis Safe at [0xD9a00176Cf49dFB9cA3Ef61805a2850F45Cb1D05](https://gnosis-safe.io/app/gno:0xD9a00176Cf49dFB9cA3Ef61805a2850F45Cb1D05/)
Artwork TBD

I confirm that
- [ ] Column `eoa` and `grade` are mandatory
- [ ] Addresses in the column `eoa` should start with `0x` and wrapped by `>` and `<`. The followings are valid examples of an `eoa` entry: 
    - `"<a href=""https://blockscout.com/xdai/mainnet/address/0xf69c45b4246fd91f17ab9851987c7f100e0273cf"" target=""_blank"">0xf69c45b4246fd91f17ab9851987c7f100e0273cf</a>"` 
    - `>0xea674fdde714fd979de3edf0f56aa9716b898ec8<`

**Comment by QYuQianchen** [comment]
Related to this issue, a GnosisSafe should be created to hold NFTs. Please provide addresses of signers.

**Comment by SCBuergel** [comment]
Thanks @QYuQianchen - I updated the comment with the target address of the newly created and tested Gnosis Safe linked above

**Comment by QYuQianchen** [comment]
@Jaguaras has already minted all NFTs. Physical ones are printed.
