### ISSUE TITLE
Dashboard for Matterhorn Testnet (& NFT distribution)

### ISSUE THREAD

**Issue by jayveq** [hoprnet/hopr-devrel#194]
### Issue deadline

Feb 25 2022

### Detailed Description

For our last testnet we need a new dashboard collecting on-chain data from our users. It should mostly resemble our last WIldhorn-v2 testnet dashboard: https://dune.xyz/hoprnet/HOPR-xDAI-Testnet-Wildhorn-v2 with a few changes: 

1. Instead of all on-chain actions, only the opening and closing of channels, as well as the redeeming of tickets should be count towards the score for the NFT rewards.
2. Instead of the with the NFT awarded address being determined by the last withdraw of a node, the score of a node should be tied to an address that funded the node initially with wxHOPR. If one address funded multiple nodes, these scores should add up (usually resulting in a higher score and reward for that address).

For any questions, please refer to Josh on Element.

**Comment by Eleonora0119** [comment]
The dashboard is available: https://dune.xyz/hoprnet/HOPR-xDAI-Testnet-Matterhorn
