### ISSUE TITLE
Update data plugins / analytics to account for incentive changes in DAO v0.3

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#202]
This is part of the DAO v0.3 epic #197 

### Issue deadline
March 21st

### Detailed Description

The system for calculating incentive payouts for the DAO experiment has been updated. Nothing has changed with the tagging system for posts, so the data will still be gathered correctly. However, to properly calculate the payouts, the data plugins in the forum will need to be updated.

The original payout scheme can be found [here](https://docs.google.com/document/d/1how4y-6C2xRib-U3gVOQ3chIIov0FvbNiHr7nnk2DO4/).

The updated scheme is [here](https://docs.google.com/document/d/1a3LfZDz8bzYa9g9v6itlVO5bI4Ow6ZGmJOZ69NoOQBk/).

The changes are:

- The weightings of the various categories have been adjusted.
- The proposals categories have been updated and clarified. The original incorrectly ignored proposals which reached the vote stage but did not win.
- A new category has been added, where tech team assigns 10% of the payout to particular users / proposals at their discretion. There is a similar category for moderators, so it should be easy to create and apply this new category.

**Comment by Eleonora0119** [comment]
Modifications:
plugin 1.
- adding parameter (hopr dao v0.3) parameter and changing line 7-13 accordingly
- support rate from 15 to 10
- from "valid_proposal_tag" removing the "hopr-official" line 34
- needs to be harmonized with the "voting stage" @thewanderingeditor  

plugin 3. 
- adding parameter (hopr dao v0.3) parameter and changing line 7-13 accordingly
- the category of "proposers" (line 45) needs to be changed @QYuQianchen

**Comment by Eleonora0119** [comment]
Changes in the plugins need to be considered:
- the sub-categories of the "PROPOSALS" category changed, new tags were introduced on the official proposals:  
https://forum.hoprnet.org/c/hopr-dao-v0-3/da0-v0-3-proposals/68
-every referendum stage proposal has the "proposal-valid" tag, plus the stage the given proposal reached in the process, such as "proposal-no-vote", "proposal-vote-stage", "proposal-vote-winner"

**Comment by QYuQianchen** [comment]
1. On the forum, v0.3 categories has sub-category under the main category. They have two different `category_id`s. All the `proposal_category` query should be updated.
2. A separate query #2 to get active participants is created https://forum.hoprnet.org/admin/plugins/explorer?id=26
3. A separate query #5 (WIP) is created https://forum.hoprnet.org/admin/plugins/explorer?id=27

**Comment by tolbrino** [comment]
Changes have been implemented in a separate repository.
