### ISSUE TITLE
Select forum users to allocate 10% tech discretionary DAO rewards

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#203]
This is part of #197 

### Issue deadline
March 25th

### Detailed Description

As part of the third HOPR DAO experiment, 10% of the rewards are to be allocated by the tech team to the users who provided the best tech ideas / contributions to the discussion. The goal of this allocation is to provide rewards to users who may not have been served well by the automated portions of the distribution (so, e.g., if an impressive user also provided the winning proposal, it's likely they've been adequately rewarded). The full incentive scheme can be found [here](https://docs.google.com/document/d/1a3LfZDz8bzYa9g9v6itlVO5bI4Ow6ZGmJOZ69NoOQBk/edit)

Any number of users can be selected, and the 10% can be distributed among those users in any weighting. To assign the rewards, please give the forum IDs and /or numbers of the selected users, and the distribution among them to @Eleonora0119 or @thewanderingeditor

Optionally, if any particular **proposal(s)** seemed impressive to the tech team, it would be useful to know to highlight in the wrap-up blog, although there would be no extra rewards for this.

**Comment by nionis** [comment]
https://forum.hoprnet.org/t/custom-names-handles-on-the-hopr-ecosystem/3713
https://forum.hoprnet.org/t/proposal-14-facilitating-sharing-of-medical-records/3881
https://forum.hoprnet.org/t/proposal-9-ssl-tls-replacement/3876

@tolbrino some of my suggestions, leaving the rest to you

**Comment by Eleonora0119** [comment]
The 4 participants: 4*0.1 allocation
https://[forum.hoprnet.org/u/emmerson_biggins/summary](http://forum.hoprnet.org/u/emmerson_biggins/summary)
https://forum.hoprnet.org/u/lastfor/summary
https://forum.hoprnet.org/u/jones_05/summary
https://forum.hoprnet.org/u/tolon
