### ISSUE TITLE
Create Season 3 Staking Website and Migrate and Update Old Website

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#206]
### Issue deadline

Staking Season 3 begins at 2pm CET on April 26th. We should be ready to go at least 24hrs in advance. Individual subtasks will have even earlier deadlines.

### Detailed Description

This is part of #207 

The HOPR staking program will move from Season 2 to Season 3 at 2pm CET on April 26th. To prepare for this change, the existing staking website needs to be migrated to stake-s2.hoprnet.org and the new Season 3 website needs to be deployed at stake.hoprnet.org.

The Season 2 website will require some UI updates to mitigate the bug in the staking contract which can cause tokens to be locked.

The Season 3 website may require some UI update to reflect the results of the NFT Audit and the implementation of the Developer NFT. These changes will need to be discussed, but could include not displaying certain NFTs in the UI, preventing the locking of certain NFTs via the UI, issuing a warning when trying to lock certain NFTs, or a combination.

### Season 2 Website Tasks

- [x] Migrate the website to stake-s2.hoprnet.org
- [x] Disable the `Claim` button in the UI with <24hrs remaining in the program (April 25th) 
- [x] Rename the `Unlock` button to `Claim & Unlock`

### Season 3 Website Tasks

- [ ] Discuss potential UI changes
   - [x] Decide UI changes needed to reflect the results of the NFT Audit (#213)
   - [ ] Decide UI changes to handle the implementation of the Developer NFT
- [x] Make UI changes
- [x] Deploy new website at stake.hoprnet.org after migration of Season 2 site

**Comment by thewanderingeditor** [comment]
It was decided that the HODLr type NFT would be excluded from Season 3 of the staking program onwards. This NFT will be ignored at the contract level, but it would be useful to update the website UI to reflect this, either by:

- Displaying a warning when people try to stake a HODLr NFT;
- Removing the ability to stake HODLr NFTs entirely; or
- Not displaying HODLr NFTs at all

**Comment by SCBuergel** [comment]
As discussed internally let's disable the `Claim` button ASAP @nionis @QYuQianchen.

**Comment by nionis** [comment]
> As discussed internally let's disable the `Claim` button ASAP @nionis @QYuQianchen.

the PR for that https://github.com/hoprnet/hopr-devrel/pull/220

**Comment by nionis** [comment]
this PR https://github.com/hoprnet/hopr-devrel/pull/221 creates the new branch used for S3, some works needs to be picked up

**Comment by thewanderingeditor** [comment]
@tolbrino The new link for "Read about HOPR staking" at the top of the page is: https://medium.com/hoprnet/780edfd4f1e1

**Comment by tolbrino** [comment]
Websites updated and deployed.
