### ISSUE TITLE
Update D.E.R.P. Website

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#208]
### Issue deadline
March 29th

### Detailed Description
Now that the third D.E.R.P. example has been published and privacy week has ended, it would be useful to update the text and links on the D.E.R.P. site to reflect its status.

- [x] Update main text based on edits from @thewanderingeditor
- [x] Add links to three medium blogs to the respective examples [1](https://medium.com/hoprnet/derp-example-1-metamask-linkability-6b26ba42072f) [2](https://medium.com/hoprnet/derp-example-2-nft-marketplace-7d3e4b4e8e2a) [3](https://medium.com/hoprnet/derp-example-3-uniswap-mev-c2a8d3417c8)

**Comment by thewanderingeditor** [comment]
Will have the necessary edits ready by morning of March 28th. Nothing extensive planned.

**Comment by tolbrino** [comment]
Done and deployed.
