### ISSUE TITLE
Pull usage data from derp.hoprnet.org

### ISSUE THREAD

**Issue by jayveq** [hoprnet/hopr-devrel#216]
### Issue deadline

To showcase the things we have done within the Hop on Board campaign, we'd like to share before it ends, ideally we would have this information by April 20th 2022.

### Detailed Description

For a further presentation of DERP, we want to highlight the usage of it. As @tolbrino already did previously, I'd like to request a graph highlighting the amount of requests done over a certain timeframe – in this case within the last three months.

If finished, or if there are any questions, they can be sent to Josh via Mail or Element.

**Comment by tolbrino** [comment]
There is no way to get historic usage data as of now. We'd have to add something to DERP to gather such information.
