### ISSUE TITLE
After syncing your claimable rewards it shows the lower amount to claim the staking rewards

### ISSUE THREAD

**Issue by Jaguaras** [hoprnet/hopr-devrel#229]
## Expected Behavior

After syncing your claimable rewards it should show at least the same amount of claimable rewards (black font in UI) + unsynced amount (blue font in UI). In the example below, that should amount to 150 HOPR + 175 HOPR = 325 HOPR.

## Current Behavior

After syncing claimable rewards, it shows a lower claimable rewards amount of tokens to claim, in this case it's 292 HOPR instead of 325 HOPR.

Before syncing:
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/73285987/166148697-9c28a21b-ee45-4b98-b773-df4cf0a2256f.png">

After syncing:
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/73285987/166148718-ce5074f0-6fc7-42aa-bbd0-0b96f9126cd2.png">

It should sync with the claimable amount of ~325 HOPR tokens, but instead it shows just ~292

## Steps to Reproduce

1. Stake some amount of tokens
2. After some time try to sync

## Screenshots

1st screenshot shows before claiming, 2nd screenshot shows the balance after the claiming process.
![telegram-cloud-photo-size-2-5429636259501948345-x](https://user-images.githubusercontent.com/73285987/165937981-df1d5879-7739-4395-877f-ab60593fc5a5.jpg)

Before claiming
![telegram-cloud-photo-size-2-5429636259501948347-x](https://user-images.githubusercontent.com/73285987/165938989-92cc23d1-8044-42a8-aa06-e3fe04d4b4d7.jpg)

After claiming
![telegram-cloud-photo-size-2-5429636259501948346-x](https://user-images.githubusercontent.com/73285987/165939043-7d758f4c-8e24-4088-8306-a5f6bd59a1a5.jpg)

**Comment by SCBuergel** [comment]
Maybe this is a pointer:
For some reason I got a smaller value for `getCumulatedRewardsIncrement` [from blockscout](https://blockscout.com/xdai/mainnet/address/0xae933331ef0bE122f9499512d3ed4Fa3896DCf20/read-contract) than what @Jaguaras received via UI at the same time.
