### ISSUE TITLE
Ping Bot

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#276]
### Description

We need to monitor node uptime in the latest release. In addition to providing data on network health, having ongoing uptime data for network participants will allow us to distribute rewards.

The simplest way to determine uptime is by regularly pinging every node in the network registry and tracking the response. 

Which each ping, the ping node(s) should work its way down the list of nodes in the network registry and attempt to ping them. The results should be recorded in a database.

This data should be publicly available so that participants can monitor the health of their own node. If possible, we should reuse the site at network.hoprnet.org

### Deadline

We need this to be finished and testable by September 12th

### Ping Nodes

One or more nodes controlled by the HOPR association should systematically and repeatedly ping every node in the network registry. Discussion is needed to determine the precise way in which a ping node should operate. See the comment below.

### Leaderboard

The results of the ping node should be recorded in a database.

At minimum, each ping attempt should generate a score of 1 for success and 0 for failure and the cumulative score for each should be tracked as a leaderboard. More data can be recorded and displayed if it would be useful for tech.

If possible, we should reuse some of the work from https://github.com/hoprnet/hopr-leaderboard
www: https://network.hoprnet.org/

**Comment by thewanderingeditor** [comment]
Some questions for tech on the precise implementation of the ping node include:

- How many ping nodes should there be?
- With what frequency should nodes ping other nodes?
- What ping strategy should be employed? (e.g., if there are multiple nodes, should each node ping each address in the registry, or should they split the load?)
- How should the ping strategy be implemented (e.g., it was suggested that heartbeat could be modified)?

**Comment by mjadach-iv** [comment]
### The way I see it:
1. We (probably Tech) setup 5 VMs on Google Cloud with 5 individial Hopr Nodes
2. I setup a DB to have peerId with scores
3. I create a script that will request peerIds from those 5 VMs and subgraph and merge them into 1 list
4. I deploy the script on the 1 or 2 VMs for making it redundant
5. I create a website that will display the results

**Comment by ausias-armesto** [comment]
I have created 5 Hopr nodes on Hetzner. The access information can be seen at [Paleochora - 1.89](https://www.notion.so/hoprnet/Paleochora-1-89-add1eefc6b774ce58dd46c042ded3bfc) filtering by creator "Michal {1-5}"

**Comment by nionis** [comment]
Created a ticket for a bug found to be tackled by tech https://github.com/hoprnet/hopr-devrel/issues/283

**Comment by mjadach-iv** [comment]
Deployed and working
