### ISSUE TITLE
Analytics for network registry waitlist

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#277]
### Description

As we move forward with the Monte Rosa public release, we need a way to assign community members to the network registry, both initially and for the planned expansions to the registry.

Waitlist access should be open only to HOPR stakers, with ordering based on scores based on NFT ownership. Tied scores will be broken by stake amount. Further ties will be broken based on time of first stake.

The waitlist should be generated using Dune.

### Waitlist Specifics

1. NFT scoring

Every staker in HOPR stake season 4 receives a score based on staked NFTs. The scoring system is similar to that used for the [Collector NFT](https://github.com/hoprnet/hopr-devrel/issues/262):

- Diamond: 4 points
- Gold: 3 points
- Silver: 2 points
- Bronze: 1 points

Because we want to prioritise earlier testers, users receive double points for their Collector and Matterhorn NFTs.

In addition, users receive a bonus point if they earned the NFT rather than buying it. An NFT is deemed to be earned if it was sent to the staking contract from the original address which received it.

2. Tied scores

After assigning NFT scores, it's certain that there will be many ties. These should be broken based on current stake, with higher stakes receiving priority.

3. Double-tied scores

It's possible that there will be participants with the same stake and NFT score. In this case, addresses which staked earlier (including Seasons 1-3) should be prioritised.

NOTE: The registry will not strictly follow the waitlist ordering, as we also want to make space for Avado and dAppNode owners and a random allocation for community members.

**Comment by MartinBenediktBusch** [comment]
Ranking is ready for review

**Comment by thewanderingeditor** [comment]
Analytics checked and complete: https://dune.com/queries/1223369
