### ISSUE TITLE
Create a Vercel project for network and assign domain

### ISSUE THREAD

**Issue by mjadach-iv** [hoprnet/hopr-devrel#279]
### Issue deadline

ASAP

### Detailed Description
Issue moved from: https://github.com/hoprnet/hopr-devops/issues/61
Please:

* create a Vercel project for network-registry (repo: https://github.com/hoprnet/hopr-network-registry)
* assign [network.hoprnet.org](http://network.hoprnet.org/) domain to it (old project should be removed from this domain)

**Comment by nionis** [comment]
Added vercel integration into https://github.com/hoprnet/hopr-network-registry and assigned network.hoprnet.org to it.
