### ISSUE TITLE
Dockerize be-script for Node Registry

### ISSUE THREAD

**Issue by mjadach-iv** [hoprnet/hopr-devrel#280]
### Issue deadline

`16/09/2022`

### Detailed Description
Moved from: https://github.com/hoprnet/hopr-devops/issues/60

1. Setup MySQL/MariaDB for the network-registry and provide Michal with credentials.
If extra funds are needed, ask Seb and Rik.

2. Setup Back-End
Docerize backend script for Node Registry and deploy it.
https://github.com/hoprnet/hopr-network-registry/tree/main/be-scripts
The ENV will be on BitWarden.
Script should run every hour, best to start at every XX:00.

3. Provide ssh access to 5 nodes created for Node Registry with a command that can be used to restart hoprd on them

**Comment by ausias-armesto** [comment]
At the meeting that we had yesterday with @mjadach-iv  and @nionis, we agreed to provide a quick solution until @mjadach-iv comes back from his holiday. On his return, we will create an epic to provide a better, consistent and complete solution to this new service.
The solution provided consisted on:
- Use one of the Hetzner servers to deploy there the docker container in charge of synchronize the http://network.hoprnet.org site.
- On the server we cloned the git repository and compile the image from there.
- Created a simple [bash script](https://github.com/hoprnet/hopr-network-registry/blob/main/be-scripts/cron.sh) to launch the docker image
- Created a cron job to launch the bash script every two hours. As you can see in the below image, the network registry dashboard is being updated every two hours
<img width="1508" alt="Captura de Pantalla 2022-09-20 a las 8 55 58" src="https://user-images.githubusercontent.com/29434949/191188175-be4da8ec-7ebf-447d-a96e-ca8934bf5b3f.png">

As mentioned in the meeting, this solution has many drawbacks:
- The deployment was done directly on the server, not through an automated process
- The deployment is incomplete as the MySQL server is hosted in an external provider
- The docker image is not published on GCP
- If @mjadach-iv needs to modify anything on the code, it will be needed to repeat all the previous steps.

**Comment by ausias-armesto** [comment]
The epic for doing it correctly has been created here:  https://github.com/hoprnet/hopr-devrel/issues/282
