### ISSUE TITLE
Create and deploy Season 5 smart contract

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/hopr-devrel#291]
- [x] Create contract
- [x] Basic testing
- [x] Perform security check with Mythril
- [x] Perform security check with Slither
- [x] Create deployment file

**Comment by QYuQianchen** [comment]
Deployed at [0xd80fbBFE9d057254d80eEbB49f17aCA66a238e2D](https://blockscout.com/xdai/mainnet/address/0xd80fbBFE9d057254d80eEbB49f17aCA66a238e2D/contracts#address-tabs)
