### ISSUE TITLE
Create and deploy Season 6 subgraph

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#311]
We need a new subgraph for the Season 6 staking contract

Unlike previous seasons, we intend for the staking website to use the subgraph more, rather than relying on RPC calls.

The following data will need to be available:

`actualLockedTokenAmount` (renamed from `actualStake`)
`cumulatedRewards`
 `claimedRewards`

### Deadline

January 11th

**Comment by QYuQianchen** [comment]
S6 subgraphs are deployed to the hosted service https://github.com/hoprnet/hoprnet/pull/4477#issuecomment-1371738684
