### ISSUE TITLE
Create and Deploy Season 8 Subgraph and Smart Contract

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#333]
The smart contract and subgraph for Season 8 need to be created and deployed

The base parameters for Season 8 are:

Base rate: 1.25%
Boost cap: 250,000
Start time: 1690372800
End time: 1694260800

# Steps

- [x] @QYuQianchen to create and deploy season 8 SC
- [x] @MartinBenediktBusch to adapt and deploy subgraph to include season 8

**Comment by QYuQianchen** [comment]
Staking S8 for production is deployed at [0x488eb03650bd2de6b4feb187f06b34ee483d81ba](https://gnosisscan.io/address/0x488eb03650bd2de6b4feb187f06b34ee483d81ba#code). Please double check.
