### ISSUE TITLE
Create dune dashboard to parse module transactions targeting channels contract

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-devrel#346]
## Description

When CORE debugging on-chain tx issues, such as https://github.com/hoprnet/hoprnet/issues/5638, or checking the cause of xDAI balance reduction for node [0xeced17c48f6b9cfe446132152ec08788e4b4279d](https://gnosisscan.io/address/0xeced17c48f6b9cfe446132152ec08788e4b4279d), it is hard to inspect the final method called by the transaction. 

Due to two reasons i) modules are only proxy instances ii) auto-decoded tx payload cannot tell further which HoprChannels method is called, we need to create a dashboard to parse channel function parameters from a module transaction call.

### Example
To better understand the issue described, there's an example of the initial input and the final expected output.
1. From the tx [0xd1b944611620d24906fdc2e2f440e1ba6f133ae725a91b30795f62c41697ebf4](https://gnosisscan.io/tx/0xd1b944611620d24906fdc2e2f440e1ba6f133ae725a91b30795f62c41697ebf4), we see the input data is 
```
0x468721a700000000000000000000000077c9414043d27fdc98a6a2d73fc77b9b383092a70000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044bda65f45000000000000000000000000eced17c48f6b9cfe446132152ec08788e4b4279d000000000000000000000000d33888a2a4cd8d4ddc6c499967934cf8111b79fc00000000000000000000000000000000000000000000000000000000
```
which can be parsed into 

| # | Name      | Type    | Data                                                                                                                                       |
|---|-----------|---------|--------------------------------------------------------------------------------------------------------------------------------------------|
| 0 | to        | address | 0x77C9414043d27fdC98A6A2d73fc77b9b383092a7                                                                                                 |
| 1 | value     | uint256 | 0                                                                                                                                          |
| 2 | data      | bytes   | 0xbda65f45000000000000000000000000eced17c48f6b9cfe446132152ec08788e4b4279d000000000000000000000000d33888a2a4cd8d4ddc6c499967934cf8111b79fc |
| 3 | operation | uint8   | 0                                                                                                                                          |

because the tx sender (node) calls method `execTransactionFromModule(address to, uint256 value, bytes data, uint8 operation)` on its module.
2. Then the "data" field
```
0xbda65f45000000000000000000000000eced17c48f6b9cfe446132152ec08788e4b4279d000000000000000000000000d33888a2a4cd8d4ddc6c499967934cf8111b79fc
```
should be parsed to

| # | Name        | Type    | Data                                       |
|---|-------------|---------|--------------------------------------------|
| 0 | self        | address | 0xeced17c48f6b9cfe446132152ec08788e4b4279d |
| 1 | destination | address | 0xd33888a2a4cd8d4ddc6c499967934cf8111b79fc |

using the ABI of function `initiateOutgoingChannelClosureSafe(address self, address destination)`

## Definition of Done
1. Create a dune table, so that for a given node address, we see a table that contains all the transactions with the parsed method, in chronological order. Method name to its 4-byte id can be found in "##Annex"

| Txn Hash | Module address | Safe address | Block number | Txn index | Parsed method name | data |
|----------|----------------|--------------|--------------|-----------|--------------------|------|

2. Create tables for each function in "Annex" so that data payload can be parsed

## Annex

- `closeIncomingChannelSafe(address self, address source)` function: 0x54a2edf5
- `finalizeOutgoingChannelClosureSafe(address self, address destination)` function: 0x651514bf
- `fundChannelSafe(address self, address account, Balance amount)` function: 0x0abec58f
- `initiateOutgoingChannelClosureSafe(address self, address destination)` function: 0xbda65f45
- `redeemTicketSafe(address self, RedeemableTicket calldata redeemable,HoprCrypto.VRFParameters calldata params)` function: 0x0cd88d72

**Comment by MartinBenediktBusch** [comment]
Added safe and module address since they were the last missing pieces to complete the ticket: https://dune.com/queries/3151076/5256774
