### ISSUE TITLE
Update Dune dashboard so that users can switch between wildhorn testnets.

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-devrel#45]
As suggested [in the comment](https://github.com/hoprnet/hoprnet/issues/2417#issuecomment-924937447), Dune dashboard needs to be updated. Ideally, users can select the test net.

- [x] Include new events (after audit)
- [x] Include HoprChannels contracts (auto deployed by CI)
- [x] Add dropdown

**Comment by jjperezaguinaga** [comment]
Important to notice, as discussed, we do not need to retroactively support `wildhorn_v1` users, just `wildhorn_v2` onwards.

**Comment by QYuQianchen** [comment]
Included new events (`Announcement(address,bytes,bytes)`, `ChannelUpdated`, `ChannelOpened` and `ChannelFunded`) and removed outdated ones (`Announcement(address,bytes)`, `ChannelUpdate` and `TokensReceived (old)`)

When a new contract for the testnet is deploy. Address of the new contract should be inserted/replaced in the code snippet of the following queries.
``` sql
WITH hopr_channels AS (
    SELECT * FROM unnest(ARRAY[
        '\x0dd7a6d4019a2bd978fe19ad9f51c08afc0a8d70', -- Sep-24-2021 02:49:35 PM +UTC 19462151 -- new testnet
        '\x3cd4b4d97dcad4ee772bc4f0fb0e7605fc86a85b'  -- Aug-25-2021 08:49:29 AM +UTC 18375520
    ]::bytea[], ARRAY [
        'Wildhorn V2', -- new testnet
        'Wildhorn V1'
    ], ARRAY [
        19462151, -- new testnet
        18375520
    ], ARRAY [
        20000000, -- new testnet
        18700550
    ]) AS t(address, deploy_time, start_block, end_block)
```
- HoprChannels polygon testnet - network overview: https://dune.xyz/queries/133225/262325
- HoprChannels polygon testnet - bidirectional view: https://dune.xyz/queries/133108/262129
- HoprChannels polygon testnet - unidirectional view (destination): https://dune.xyz/queries/133217/262256
- HoprChannels polygon testnet - unidirectional view (source): https://dune.xyz/queries/133162/262133
- HoprChannels polygon testnet - individual view: https://dune.xyz/queries/132832/261610
- HoprChannels polygon testnet - ChannelUpdate calls over time: https://dune.xyz/queries/134938/2656703
- HoprChannels polygon testnet - Annoucement (times): https://dune.xyz/queries/136111/268592
- HoprChannels polygon testnet - Annoucement (intervals): https://dune.xyz/queries/136338/268658
- HoprChannels polygon testnet - Function calls: https://dune.xyz/queries/141001/278280

**Comment by QYuQianchen** [comment]
Backward support (for wildhorn v1) is included, as it did not add much extra work.
