### ISSUE TITLE
Automatically verify smart contracts

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-devrel#52]

**Comment by jjperezaguinaga** [comment]
Removing this from #12 and making it instead a pipeline task for our new pipeline improvement epic - https://github.com/hoprnet/hoprnet/issues/2605

**Comment by jjperezaguinaga** [comment]
Removing assignee and moving to `icebox` as this is >3 months old w/o activity.

**Comment by QYuQianchen** [comment]
Close this issue as most of the contracts are migrated to monorepo and the auto-verification has been fixed.
