### ISSUE TITLE
Change from manually importing logs to GCP Logger API

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-devrel#74]
Update the code with [GCP Logger API](https://cloud.google.com/logging/docs/reference/libraries#client-libraries-install-python)

- [x] #75

**Comment by QYuQianchen** [comment]
instance id `7872204418567022049` and `8212280380033896655`

**Comment by QYuQianchen** [comment]
[downloaded-logs-20211101-091425.csv](https://github.com/hoprnet/hopr-devrel/files/7451666/downloaded-logs-20211101-091425.csv)

**Comment by Eleonora0119** [comment]
- 8212280380033896655 was active the following days (29 Oct - 2 Nov) 
- data extraction is only possible sequentially in 1-2 days steps

**Comment by Eleonora0119** [comment]
the activity of the 8212280380033896655 node between 27 Nov and 17 Oct:
open:
16Uiu2HAmHsB2c2puugVuuErRzLm9NZfceainZpkxqJMR6... | 1 | 2021-10-28 08:26:03.298 (with change in the balance)

close:
16Uiu2HAmBCcc822eURPRu6YXuSNmPZn2tJ1nEePNPUsz8... | 1 | 2021-10-28 08:29:37.100 (change in the balance)
16Uiu2HAmHsB2c2puugVuuErRzLm9NZfceainZpkxqJMR6... | 4 | 2021-10-30T07:34:37.092Z (no change in the balance) / 2021-10-30T07:37:41.534Z (no change in the balance) / 2021-10-30T07:37:53.477Z (no change in the balance) / 2021-10-30 22:04:12.883 (change in the balance)
