### ISSUE TITLE
Node and channel coverage selected by CT node.

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-devrel#80]
In CT path selection, the probability of selecting the first hop is uniformed among all the open channels coming out of CT nodes. For the second and third hop, it uses "Importance Score" as weight, meaning that the probability of choosing a channel for the next hop

**Comment by SCBuergel** [comment]
The output of this tasks could also be compared against the simulations and see if there are large discrepancies, if yes, we should assess where the differences come from.
