### ISSUE TITLE
NFT minting process and improvements

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-devrel#86]
# Introduction
See #85. As we continue to mint NFTs for our users, the following issue describes a series of improvements we need to do internally to ensure the minted NFTs are properly minted with the adequate artwork used. The goal of this ticket is to fine-tune these tasks, patch existing issues previous steps did not follow, and ensure the existing ones are under HOPR's control and anyone authorized can update them when needed.

# Task description

## Patch Bugs
- [x] #87
- [x] #90

## Improve process
- [x] #91

## Organization
- [ ] #92
- [ ] #93

**Comment by nionis** [comment]
Closing in favor of https://github.com/hoprnet/hopr-devrel/issues/111
