### ISSUE TITLE
`virtual_stake` (investors locked in HOPR amount) is not displayed in the UI

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-devrel#9]
# Introduction
Now that we have our first HOPR token unlock, we want to show the community how many of these investors will continue to lock their HOPR tokens via our staking contract. Currently, our [staking](https://github.com/hoprnet/hopr-stake/blob/main/contracts/HoprStake.sol#L49) contract only displays "virtual staking" per account, but not globally.

# Task Description
Iterate over the list of registered investors and reduce their `virtualLockedTokenAmount` value for a total.

**Comment by jjperezaguinaga** [comment]
Removing assignee and moving to `icebox`, although this could be closed already as it's not a practical task and could already had been implemented in a different way.
