### ISSUE TITLE
Migrate existing NFTs metadata IPFS to our team IPFS account

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-devrel#92]

**Comment by tolbrino** [comment]
Can you please put all ipfs links here so we can pin them on other accounts? That way we don't have to "migrate" stuff.

**Comment by jjperezaguinaga** [comment]
![image](https://user-images.githubusercontent.com/1128312/143889856-c7142815-54d5-499b-a9fd-b8233aa0b00f.png)

Already migrated it to our account (credentials in the vault under tech@hoprnet.org, shared to `comms` folder), nevertheless, can be found here (and they are already pinned, see https://gateway.pinata.cloud/ipfs/QmamaXGA8RTT2znJ6x1TnfYHQ7R7vEGixszxoPy5xQoGeu/Bronze.png)

NFT - DAO_v2 11/29/2021 22.0 MB | QmamaXGA8RTT2znJ6x1TnfYHQ7R7vEGixszxoPy5xQoGeu | False | More
-- | -- | -- | --
NFT - PuzzleHunt_v1 11/29/2021 10.8 MB | QmbA7dPh1aefPp9xMau7aP2tvmEbwxrXTjUdmnMeniNBpd | False | More
NFT - PuzzleHunt_v2 11/29/2021 10.8 MB | QmVA9KpoDpY5JgaaJvTQVz4ppyYtYwcxU7JWcAPBfzp9ts | False | More
NFT - Wildhorn_v2 11/29/2021 12.3 MB | QmUdi8CTTmgpj8DrKh2yzoeyb6pVEFKgV3hjaTPmG8Bzn3 | False | More
NFT - Treasure 11/29/2021 2.1 MB | QmTtBYHggXQQETNF9AecCpC8xfBM7G4f6PesMTZgmx2Uh9 | False | More
NFT - Map 11/29/2021 2.5 MB | QmPF24DfjPirWY4n3yCvoYtsRJNzc9SEzStGrYwTnVtq73 | False | More
NFT - PuzzleHunt_v1 11/29/2021 6.9 MB | QmZMSLE1RH7QSGshWLzNz6sUZ74xUrYW4F8niTL9vvHjqL | False | More
NFT - Wildhorn_v1 11/29/2021 11.4 MB | QmdCQAsu8MnnbubWoVovpoz6uhW7oNmrijm6Kt4iSK9zK4 | False | More
NFT - HODLr 11/29/2021 2.2 MB | QmfTu5ySUJocr96cN3Q5UaP2pKSgkfESvKwSxrM5HA1xKL | False | More
NFT - Demo 11/29/2021 1.5 MB | QmU33aCfa8L8Ch6jxHci4HYzVCXEn7MgDSKpNgdbWtKKnK | False | More

**Comment by jjperezaguinaga** [comment]
Completed [here](https://github.com/hoprnet/hopr-devrel/issues/92#issuecomment-981709573), closing.
