### ISSUE TITLE
Rename treasure hunt NFT's 

### ISSUE THREAD

**Issue by Jaguaras** [hoprnet/hopr-devrel#99]
## Deadline

ASAP

## Issue

Users can't see their NFTs on staking UI, because it can't find Puzzle NFT's, see the screenshots bellow. This is urgent, because they can't boost their stake.

## Solution

- Rename from `Gold` to `Gold - Week 5` 
- Rename from `Bronze` to `Bronze - Week 5` 

**Update (Rename also PuzzleHunt_v1):** 

- Rename from `Gold` to `Gold - Week 3` 
- Rename from `Bronze` to `Bronze - Week 3` 

## Screenshot 

`0x253a1dc6BBad8A62a8e8F7B21214FEa2B78CB77E` - this member got puzzle NFT, from the console logs it looks like it can't find `PuzzleHunt_v2`

![telegram-cloud-photo-size-4-5776301276328474316-y](https://user-images.githubusercontent.com/73285987/140523438-368fdf9d-25c7-4155-8a76-5b0236662863.jpg)

`0x5Fe9a92531Fe648666551a6cBaE2A7b817249c52` - same with another user.

![telegram-cloud-photo-size-4-5776322489171949138-y](https://user-images.githubusercontent.com/73285987/140523792-8d826cf3-f090-4dd2-b558-a67785581996.jpg)

**Comment by Jaguaras** [comment]
@jjperezaguinaga Please take a look at updated version on issue. We also need to rename PuzzleHunt_v1

**Comment by tolbrino** [comment]
@Jaguaras Please close this ticket once you verified the issue is fixed.

**Comment by Jaguaras** [comment]
Issue was solved, everything is working fine.
